miLavadora=Lavadora(20,"","",40,31)
# miLavadora.get_atributos()
# miLavadora.getCarga()
# print("________________________________________")
# miTele=Television(100,"azul","D",20,41,False)
# miTele.get_atributos()
# miTele.get_resolucion_sintonizador()
# print("________________________________________")